revoke delete on table "public"."rate_limits" from "anon";

revoke insert on table "public"."rate_limits" from "anon";

revoke references on table "public"."rate_limits" from "anon";

revoke select on table "public"."rate_limits" from "anon";

revoke trigger on table "public"."rate_limits" from "anon";

revoke truncate on table "public"."rate_limits" from "anon";

revoke update on table "public"."rate_limits" from "anon";

revoke delete on table "public"."rate_limits" from "authenticated";

revoke insert on table "public"."rate_limits" from "authenticated";

revoke references on table "public"."rate_limits" from "authenticated";

revoke select on table "public"."rate_limits" from "authenticated";

revoke trigger on table "public"."rate_limits" from "authenticated";

revoke truncate on table "public"."rate_limits" from "authenticated";

revoke update on table "public"."rate_limits" from "authenticated";

revoke delete on table "public"."rate_limits" from "service_role";

revoke insert on table "public"."rate_limits" from "service_role";

revoke references on table "public"."rate_limits" from "service_role";

revoke select on table "public"."rate_limits" from "service_role";

revoke trigger on table "public"."rate_limits" from "service_role";

revoke truncate on table "public"."rate_limits" from "service_role";

revoke update on table "public"."rate_limits" from "service_role";

revoke delete on table "public"."users" from "anon";

revoke insert on table "public"."users" from "anon";

revoke references on table "public"."users" from "anon";

revoke select on table "public"."users" from "anon";

revoke trigger on table "public"."users" from "anon";

revoke truncate on table "public"."users" from "anon";

revoke update on table "public"."users" from "anon";

revoke delete on table "public"."users" from "authenticated";

revoke insert on table "public"."users" from "authenticated";

revoke references on table "public"."users" from "authenticated";

revoke select on table "public"."users" from "authenticated";

revoke trigger on table "public"."users" from "authenticated";

revoke truncate on table "public"."users" from "authenticated";

revoke update on table "public"."users" from "authenticated";

revoke delete on table "public"."users" from "service_role";

revoke insert on table "public"."users" from "service_role";

revoke references on table "public"."users" from "service_role";

revoke select on table "public"."users" from "service_role";

revoke trigger on table "public"."users" from "service_role";

revoke truncate on table "public"."users" from "service_role";

revoke update on table "public"."users" from "service_role";

alter table "public"."rate_limits" drop constraint "rate_limits_pkey";

alter table "public"."users" drop constraint "users_pkey";

drop index if exists "public"."idx_rate_limits_user_function_time";

drop index if exists "public"."rate_limits_pkey";

drop index if exists "public"."users_pkey";

drop table "public"."rate_limits";

drop table "public"."users";


  create table "public"."players" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "player_name" character varying,
    "total_games_played" bigint,
    "total_games_won" bigint,
    "total_correct_answers" bigint,
    "total_incorrect_answers" bigint,
    "total_correct_daily_doubles" bigint,
    "total_incorrect_daily_doubles" bigint,
    "total_correct_final_jeopardies" bigint,
    "total_incorrect_final_jeopardies" bigint,
    "current_balance" bigint,
    "total_money_earned" bigint
      );


alter table "public"."players" enable row level security;

alter table "public"."games" add column "created_by" text;

drop sequence if exists "public"."rate_limits_id_seq";

CREATE UNIQUE INDEX users_pkey ON public.players USING btree (id);

alter table "public"."players" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

grant delete on table "public"."players" to "anon";

grant insert on table "public"."players" to "anon";

grant references on table "public"."players" to "anon";

grant select on table "public"."players" to "anon";

grant trigger on table "public"."players" to "anon";

grant truncate on table "public"."players" to "anon";

grant update on table "public"."players" to "anon";

grant delete on table "public"."players" to "authenticated";

grant insert on table "public"."players" to "authenticated";

grant references on table "public"."players" to "authenticated";

grant select on table "public"."players" to "authenticated";

grant trigger on table "public"."players" to "authenticated";

grant truncate on table "public"."players" to "authenticated";

grant update on table "public"."players" to "authenticated";

grant delete on table "public"."players" to "service_role";

grant insert on table "public"."players" to "service_role";

grant references on table "public"."players" to "service_role";

grant select on table "public"."players" to "service_role";

grant trigger on table "public"."players" to "service_role";

grant truncate on table "public"."players" to "service_role";

grant update on table "public"."players" to "service_role";


  create policy "Enable insert for authenticated users only"
  on "public"."games"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable select for authenticated users only"
  on "public"."games"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."games"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Enable insert for authenticated users only"
  on "public"."players"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable select for authenticated users only"
  on "public"."players"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."players"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Insert, Select, and Delete Data for Auth Users 1txgq_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'data'::text));



  create policy "Insert, Select, and Delete Data for Auth Users 1txgq_1"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'data'::text));



  create policy "Insert, Select, and Delete Data for Auth Users 1txgq_2"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using ((bucket_id = 'data'::text));



  create policy "Insert, Select, and Delete Games for Auth Users 1mf269_0"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'games'::text));



  create policy "Insert, Select, and Delete Games for Auth Users 1mf269_1"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'games'::text));



  create policy "Insert, Select, and Delete Games for Auth Users 1mf269_2"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using ((bucket_id = 'games'::text));



  create policy "Select Scripts for Auth Users vuzwg8_0"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'scripts'::text));



